version: '3.7'

services: 
  portfolio_dev:
    build:
      context: .
      dockerfile: dockerfile.dev
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - .:/app
    environment:
      - ENV=development
