version: '3.7'

services: 
  portfolio_frontend:
    container_name: portfolio_frontend
    build: 
      context: ./nextjs-frontend
      dockerfile: next.dockerfile
    depends_on:
      - portfolio_backend

  portfolio_backend:
    container_name: portfolio_backend
    build: 
      context: ./backend
      dockerfile: django.dockerfile 
    image: portfolio_backend
    env_file: ./config/.env

  portfolio_caddy:
    image: caddy:latest
    restart: unless-stopped
    container_name: portfolio_caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - portfolio_backend
      - portfolio_frontend
