name: Go
on:
 push:
   branches:
     - 'main'

permissions:
  packages: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4  # Consistent version for checkout
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - name: Install dependencies
        run: go mod tidy  # Use go mod tidy for dependencies
      - name: Build
        run: go build -v ./...
      - name: Test with the Go CLI
        run: go test ./...

  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Consistent version for checkout

      - name: Set short git commit SHA
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: https://index.docker.io/v1/  # Use Docker Hub by default or your private registry
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            cbasny/portfolio:prod
            cbasny/portfolio:${{ steps.vars.outputs.COMMIT_SHORT_SHA }}  # Optional tag based on commit
         tags: cbasny/portfolio:prod
